version: '3'

tasks:
  generate:
    dir: './cmd/generate_testdata'
    cmds:
      - go generate .

  lint:
    cmds:
      - golangci-lint run ./...
      - golangci-lint run ./cmd/...
      - golangci-lint run ./examples/...

  test:
    cmds:
      - go test -v -cover ./...
      - go test -v -cover ./cmd/...
      - go test -v -cover ./examples/...
